//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace login
{
    public partial class eStatement
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label txtdissue;
        protected global::System.Web.UI.WebControls.Label lblMembership;
        protected global::System.Web.UI.WebControls.Label lblMemberName;
        protected global::System.Web.UI.WebControls.Label lblSlogan;
        protected global::System.Web.UI.WebControls.Image imgBanner1;
        protected global::System.Web.UI.WebControls.Image imgBanner2;
        protected global::System.Web.UI.WebControls.Image imgBanner3;
        protected global::System.Web.UI.WebControls.Image imgBanner4;
        protected global::System.Web.UI.WebControls.Image imgBanner5;
        protected global::System.Web.UI.WebControls.Image imgBanner6;






        // ... add the rest as needed

    }
}
